*** Variables ***

${BASE_URL}    https://serverest.dev
${LOGIN}    /login
${EMAIL_ADMIN}    juliamachado_6ba15bee-8b28-4608-9af8-cabae8f75322@hotmail.com
${PASSWORD_ADMIN}    8o9lbRyuvf9M
${EMAIL_USER}    juliamachado_137828c8-3114-4729-bfdd-34309dd88e45@hotmail.com
${PASSWORD_USER}    U7%q33
${EMAIL_INVALID}    fulanofalha@qa.com
${EMAIL_EMPTY}    ${EMPTY}
${PASSWORD_INVALID}    teste25
${PASSWORD_EMPTY}    ${EMPTY}